### PR TITLE
Debugging coverage reports

### PR DESCRIPTION
**Pull request by stevepeak**
I've tagged this repo to store raw uploads to see what is happening. Created this PR to trigger a travis build. Thank you!

### CODE REVIEW

**Comment by stevepeak** [comment]
I've got the repo tagged to store raw reports and updated the one online. I'll return here when a report can get uploaded again. Thank you!

**Comment by nelsonic** [comment]
@stevepeak no idea why this PR is failing. did you fork off the latest master? (your `.travis.yml` *appears* to have the latest secure value for the RedisCloud URL...) 

What I don't understand is why the coverage report does not total the figures it sees...
codecov-84-percent

I'd understand if the coverage was counting the /test files or the /server.js but then it should say that...
my understanding was that you are simply sending the lcov report to CodeCov at the end of the Travis Job... is this incorrect? thanks!

**Comment by stevepeak** [comment]
There are extra files that are being uploaded that are effecting coverage. Can you please submit coverage to Codecov again so I can download the raw coverage uploaded. Thank you! I'll get to the bottom of this.

**Comment by nelsonic** [comment]
@stevepeak any insight/progress tracking down why we are seeing less coverage than expected? 
We *really* want to start switching to CodeCov for our projects and teaching people to use it... http://www.foundersandcoders.com/academy/ 
Thanks for your time! :clock1030:

**Comment by stevepeak** [comment]
Hey @nelsonic I do, sorry for the delay (heavy on support as of late). There seems to be extra reports uploaded that are throwing it off. I'll jump on this now, back in a couple...

**Comment by nelsonic** [comment]
Sweet! :lollipop: 
I realise you're busy from your https://github.com/stevepeak?tab=activity
Really appreciate you making time. :+1:

**Comment by stevepeak** [comment]
> Here is the [raw upload](https://codecov.s3.amazonaws.com/repos/D7580D71F2BA06E7777971163585A473/raw/upload:1440683349.383664.txt) for d1c7d8b

#### Files in upload
- node_modules/codeclimate-test-reporter/test/fixtures/lcov.info **this one is throwing it off**
-  coverage/lcov.info **good**
-  coverage/coverage.json (if ES6: then can cause issues)
- node_modules/istanbul/lib/command/check-coverage.js **ignored**

#### Temporary fix
```diff
 after_success:
-    codecov
+   codecov --file coverage/lcov.info --disable search
```
> When I update the uploader you can return to simply `codecov`.

### I need to fix
The uploader needs to ignore `node_modules`. I'm not sure how that slipped my eye...

----

I appreciate your patience so much! I work hard to make this product great and having customers like you show patience and respect is so motivating. Hats off to you! :tophat:

**Comment by nelsonic** [comment]
@stevepeak can you add that line to your PR?
or just copy paste this into the `.travis.yml`
```yml
language: node_js
node_js:
  - 0.12
services:
  - redis-server
env:
  global:
  - secure: "cX6SVlb9D60NLbMYg7Vw5OlV9eUHJEZDyj9dsMXaSYKD/uSUJUhq+f6FWa/DJsneNCydBLSnoWJT6aiMsbhas5qDHl/lVkzonOC6sOV6Dbpjs8bXLPd1NyYvRYEltm6Gb8TDq/29IfMXahmnsCwiDcHrmcyHwdlpaso9jx0IvB9g1Xu4Otwn48VomOL/y+EY08fWvw9Wkg3aWRTenV6GcTdw1vj7J/RxBdX7TY3wUytZ6PHx94jW5GFQ55UpELT6YM6EDUrHPfLYQCCBMyvXe789iDsGuxkW7c24QE4M5tNhgwWplgXyHIoTDygIoUrTCC9KNNqt7EAyOnCYGjCHfvDQtTnlouD/fQsNXpWnBv+slrKltCkAgXTcRrZKlN2lH+h8IHcge381LSgTDR1socY5lay0a0V3mLAuU9LtrXSpo0BNFLwDc+MsnGGCtlH5ex1czN4gkdbRIuU+lASDEsK5IcnGb1K8tsaFOJazHH6vRgnZzuQMTDolXeQ7pSHu/NDcOflOigUInhvBFWhDGGHXEYEixPtvZfDNSLIQTF+L31dIn6XBQPlR4ShNezAko9aZZxpMjjFc6i/IEdpuduCQSJuYQyJGgT+F+AAccbUzHzHqKclcAdwn+M/xlCd3Doq2YIAanP4AxOJcSyciJQiHOxRKGH//1K32n/jCTSo="
before_install:
  - pip install --user codecov
after_success:
  - codecov  --file coverage/lcov.info --disable search
```

Thanks!

**Comment by nelsonic** [comment]
Ok. the Travis Build is failing because the the value for the `REDISCLOUD_URL is not being set on the fork ... this is a Travis issue. Merging this PR and will sort it out on my end.

**Comment by stevepeak** [comment]
Awesome! I'll be deploying the fixes to the uploader later today.

**Comment by nelsonic** [comment]
@stevepeak we're *really* excited to see some *innovation* in the code coverage tracking tools! 
I know its nerdy. but I'm stoked! :+1:

**Comment by nelsonic** [comment]
As predicted it Travis was choking on the fact that your fork and works fine once merged into master: https://travis-ci.org/nelsonic/hits/builds/77680179 :+1:

**Comment by stevepeak** [comment]
@nelsonic :) Love the excitement! You just wait to see what I have in-store for you! I've got some cool ideas with coverage that will help developers speed up their workflow. I'm sure you've seen the browser extensions right?

**Comment by nelsonic** [comment]
Yes, seen it. looks great! We look forward to what's next! :+1:

**Pull request merged**
